version: '3.8'

services:
  slack-knowledge-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8000
      # Slack Configuration (Required - must be provided via .env file)
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_USER_TOKEN=${SLACK_USER_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      # LLM Configuration (At least one API key required)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEFAULT_LLM_PROVIDER=${DEFAULT_LLM_PROVIDER:-openai}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o}
      - MAX_CONTEXT_TOKENS=${MAX_CONTEXT_TOKENS:-8000}
      # Query Configuration
      - MAX_HISTORY_DAYS=${MAX_HISTORY_DAYS:-90}
      - DEFAULT_QUERY_LIMIT=${DEFAULT_QUERY_LIMIT:-50}
      - MAX_QUERY_LIMIT=${MAX_QUERY_LIMIT:-200}
      # Memory Configuration (matching .env.example)
      - MEMORY_ENABLED=${MEMORY_ENABLED:-true}
      - MEMORY_MAX_TOKENS=${MEMORY_MAX_TOKENS:-200000}
      - MEMORY_MAX_MESSAGES=${MEMORY_MAX_MESSAGES:-200}
      - MEMORY_SESSION_TTL_MINUTES=${MEMORY_SESSION_TTL_MINUTES:-60}
      - MEMORY_CLEANUP_INTERVAL_MINUTES=${MEMORY_CLEANUP_INTERVAL_MINUTES:-10}
      # Session Configuration (matching .env.example)
      - SESSION_MAX_SESSIONS=${SESSION_MAX_SESSIONS:-1000}
      - SESSION_MAX_SESSIONS_PER_USER=${SESSION_MAX_SESSIONS_PER_USER:-10}
      # Logging Configuration (Docker-optimized)
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - FILE_LOGGING=${FILE_LOGGING:-false}
      - CONSOLE_LOGGING=${CONSOLE_LOGGING:-true}
      - LOG_DIR=/app/logs
    volumes:
      - ./config:/app/config:ro
      - logs:/app/logs
    networks:
      - slack-agent-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:8000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Future: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - slack-agent-network
  #   restart: unless-stopped

networks:
  slack-agent-network:
    driver: bridge

volumes:
  logs:
    driver: local