version: '3.8'

services:
  slack-knowledge-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8000
      # Required Slack Configuration (must be provided via .env file)
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_USER_TOKEN=${SLACK_USER_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      # Required LLM Configuration (at least one API key required)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o}
    volumes:
      - logs:/app/logs
    networks:
      - slack-agent-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:8000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Future: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - slack-agent-network
  #   restart: unless-stopped

networks:
  slack-agent-network:
    driver: bridge

volumes:
  logs:
    driver: local